### ISSUE TITLE
Notification Pop-Up Dismissal Time Issue

### ISSUE THREAD

**Issue by ha7shu** [JSM33T/thecoffeeroom.in#8]
Currently , the notification pop-up remains visible for a longer duration than necessary. It would be better if the notification pop-up gets dismissed after 5 seconds automatically and it wouldn't be sort of annoying.

**Comment by JSM33T** [comment]
Thanks for the suggestion !!On it!

**Comment by JSM33T** [comment]
dismissal timeout is now 5s. it will be reflected in the next build 
[commit 53ccf22](https://github.com/JSM33T/theCoffeeroom.in/commit/53ccf22adbda2255d55067ee79fa15d1a55e64cd)
